# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749da651a60054c1d95776313f64927e24117b1c8f6401d669cfcaf0605c07e96f02b511c4b850f5a37203d9bca35501f70d0afe3fca91dcb408542317db7bb7

test:
  secret_key_base: 7ac31e7950f449cb6d3c9db5e8efbc84a2fb89a9304be29fe2fe18882d87293227281bb7950d3cc239e52d3b77604121ca16a8f5d57ff1c73d4e9a4cd4a9b471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
